author = "Flor Holvoet"
baseurl = "https://www.florholvoet.be/"
canonifyurls = true
copyright = "Copyright © 2019 Flor Holvoet"
paginate = 3
theme = "alageek"
title = "Flor Holvoet"

[params]
copyright = "Copyright © 2019 Flor Holvoet"
copyrightUrl = "https://www.florholvoet.be/"
faviconfile = "/favicon.ico"
latestpostcount = 5
logofile = "/avatar.jpg"
highlightjs = true

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
