author = "Flor Holvoet"
baseurl = "https://www.florholvoet.be/"
canonifyurls = true
paginate = 3
theme = "alageek"
title = "Flor Holvoet"

[params]
copyright = "Flor Holvoet"
copyrightUrl = "https://www.florholvoet.be/"
faviconfile = "/favicon.ico"
latestpostcount = 5
logofile = "/avatar.jpg"
highlightjs = true

[[menu.primary]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/florholvoet/"
weight = 10

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 20
